---
- hosts: localhost
  tags: packages,sudo
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml

- hosts: localhost
  tags: user,config
  connection: local
  become: false
  tasks:
    - include: tasks/git.yml
    - include: tasks/alias.yml

    
