---
- hosts: localhost
  tags: packages,sudo
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
  roles:
    - base
    - vscode
    - spotify
    - logseq
    - flameshot

- hosts: localhost
  tags: user,config
  connection: local
  become: false
  roles:
    - git
    - bashrc

    
