- name: install apt packages
  tags: screenshot
  apt:
    name: 
      - flameshot

# TODO: key binding for <ctrl><shift>p to run /usr/bin/flameshot gui
# TODO: create something to change flameshot configuration, see flameshot config commandcd