- name: install apt packages
  apt:
    name: 
      - python3.10-venv
      - htop
      - tree
      - tmux
      - mc

- name: remove default programs
  apt:
    name:
      - aisleriot 
      - gnome-sudoku 
      - mahjongg 
      - gnome-mahjongg 
      - ace-of-penguins 
      - gnomine 
      - gbrainy 
      - gnome-mines
      - libreoffice-common
      - thunderbird*
      - transmission*
    state: absent
      
